// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh4Yl_QomGwcsb56sv9FX4xFUHOTgXnN0',
    appId: '1:616121433233:web:3738347151c8c7eee29330',
    messagingSenderId: '616121433233',
    projectId: 'xchange-5783f',
    authDomain: 'xchange-5783f.firebaseapp.com',
    storageBucket: 'xchange-5783f.firebasestorage.app',
    measurementId: 'G-8Y7R6DJZ02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfPHlkC_LSNt70oELypNpp4gyfGe4L48',
    appId: '1:616121433233:android:05745b8c35eeb3eee29330',
    messagingSenderId: '616121433233',
    projectId: 'xchange-5783f',
    storageBucket: 'xchange-5783f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr26GBnaa0xMwsm6lKx8rRY7rCn7C94tM',
    appId: '1:616121433233:ios:06cb59999d2c12d3e29330',
    messagingSenderId: '616121433233',
    projectId: 'xchange-5783f',
    storageBucket: 'xchange-5783f.firebasestorage.app',
    iosBundleId: 'com.example.solicitudesMovilidadAcademica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr26GBnaa0xMwsm6lKx8rRY7rCn7C94tM',
    appId: '1:616121433233:ios:06cb59999d2c12d3e29330',
    messagingSenderId: '616121433233',
    projectId: 'xchange-5783f',
    storageBucket: 'xchange-5783f.firebasestorage.app',
    iosBundleId: 'com.example.solicitudesMovilidadAcademica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh4Yl_QomGwcsb56sv9FX4xFUHOTgXnN0',
    appId: '1:616121433233:web:357f497411b45debe29330',
    messagingSenderId: '616121433233',
    projectId: 'xchange-5783f',
    authDomain: 'xchange-5783f.firebaseapp.com',
    storageBucket: 'xchange-5783f.firebasestorage.app',
    measurementId: 'G-BR25357VT1',
  );
}
